### ISSUE TITLE
Kan Totemapp niet installeren vanuit Google Play Store

### ISSUE THREAD

**Issue by Waterboy1602** [ScoutsGidsenVL/totem-app-2023#1]
Ik ondervind problemen bij het installeren van de nieuwe Totemapp versie. Tijdens het installeren krijg ik volgende foutmelding: "Can't install Totemapp". 

Ik vermoed dat dit te maken heeft met dat ik in het bezit ben van een Google Pixel 7 en deze enkel 64-bit apps ondersteunt. Waarschijnlijk werd de nieuwe versie niet gecompiled voor 64-bit. 

Ik heb zelf al eens geprobeerd om de laatste code te builden en er een app bundle van te maken. Die build kan ik wel perfect installeren op mijn gsm. 

Kan er eens nagekeken worden of bij de app bundle op de Google Play Store effectief de 64-bit build ontbreekt?

![Google Play Store foutmelding](https://github.com/ScoutsGidsenVL/totem-app-2023/assets/24163882/572f6f27-c69f-4c9a-8966-b7b9671acbac)

**Comment by mstuyven** [comment]
@Waterboy1602 Bizar, op Play Console staat bij de app bundle `Native platforms: arm64-v8a, armeabi-v7a, x86_64` en ik zie ook dat er een stuk of 20 installs zijn op Pixel 7 devices.

Als je zelf de app kan builden en installeren, welke versie van Flutter heb je en welke commands voer je precies uit?

**Comment by Waterboy1602** [comment]
Ik probeerde om de foutmelding opnieuw te krijgen door de Totemapp te verwijderen en terug te installeren, maar ik kreeg 
 niet meer dezelfde foutmelding. Nu lukt het om de Totemapp probleemloos te installeren. Geen idee wat er veranderd is.

Van mijn part mag dit probleem gesloten worden.

P.S. Mijn Flutter versie is V3.10.6 en commando dat ik heb uitgevoerd is `flutter build appbundle` om dan met [bundletool](https://github.com/google/bundletool) de .aab om te zetten naar een .apks
